ready = ->
  $('.picture').each ->
    $pic = $(this)

    getItems = ->
      items = []
      $pic.find('a').each ->
        $href = $(this).attr('href')
        $size = $(this).data('size').split('x')
        $width = $size[0]
        $height = $size[1]
        item = 
          src: $href
          w: $width
          h: $height
        items.push item
        return
      items

    items = getItems()
    $pswp = $('.pswp')[0]
    $(document).on 'click', 'figure', (event) ->
      event.preventDefault()
      $index = $(this).index()
      options = 
        index: $index
        bgOpacity: 0.9
        showHideOpacity: true
      # Initialize PhotoSwipe
      lightBox = new PhotoSwipe($pswp, PhotoSwipeUI_Default, items, options)
      lightBox.init()
      return
    return

  

# ---
# generated by js2coffee 2.1.0
  
$(document).ready(ready)
$(document).on('page:load', ready)